[build-system]

[project]
requires-python = ">=3.12"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.0.1"
update_changelog_on_bump = true
major_version_zero = true

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
